import {prepareNxt} from './nxt-import.js';
import {groups,variants,searchProducts} from './product-search.js';
import {installInventory} from './inventory.js';
import {money,number,clone,roundProduct,totals,checkQuote,normalizeProducts,parsePrice} from './core.js';
import {stockSuggestions} from './stock-suggestions.js';
import {installCloud} from './cloud.js';
import {fold} from './product-search.js';
import {loadGateData,gateAppendixHTML,gateSample} from './gate.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='stc-quote-v1';
let inventory,cloud;
let sample,catalog,state,company,saved=[],storageOK=true,toastTimer,busy=false,importBook,importRows;
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Bangkok'});
const fresh=()=>({id:crypto.randomUUID(),number:'BG-STC-'+today().replaceAll('-','')+'-'+Math.random().toString(36).slice(2,5).toUpperCase(),date:today(),customer:'',phone:'',address:'',preparedBy:'',items:[],type:'smart',mode:'sum',promo:'',discount:0,vat:'included',warranty:'',validity:'',note:'',company:clone(company)});
function tell(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',5000);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({schemaVersion:1,company,catalog,state,saved}));$('#saveState').textContent='Đã lưu nháp trên thiết bị';storageOK=true;}catch(e){storageOK=false;$('#saveState').textContent='Chưa lưu được — tải bản sao lưu';tell('Bộ nhớ trình duyệt đầy hoặc bị chặn. Hãy tải bản sao lưu.');}}
function confirmAction(title,text){return new Promise(resolve=>{const d=$('#confirmDialog');$('#dialogTitle').textContent=title;$('#dialogText').textContent=text;d.returnValue='';$('#okDialog').onclick=()=>d.close('ok');$('#cancelDialog').onclick=()=>d.close('cancel');d.onclose=()=>resolve(d.returnValue==='ok');d.showModal();});}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='catalog')renderCatalog();if(id==='history')renderSaved();if(id==='settings')renderCompany();}
function safeLogo(s){return typeof s==='string'&&(s==='assets/stc-logo.jpg'||/^data:image\/(?:png|jpeg|webp);base64,/.test(s))?s:'assets/stc-logo.jpg';}
function quoteHead(q){const c=q.company,e=esc;const companyLogo=safeLogo(c.logo);const fptLogo=c.fptLogo&&/^data:image\/(?:png|jpeg|webp);base64,/.test(c.fptLogo);const partner=q.type==='gate'?'<div class="gate-word">CỔNG TỰ ĐỘNG<span>AB GATE · DEA Italy</span></div>':fptLogo?`<img class="fpt-logo" src="${e(c.fptLogo)}" alt="FPT Smart Home">`:'<div class="fpt-word">FPT <span style="font-weight:400">Smart Home</span></div>';return `<header class="quote-head"><div><img src="${e(companyLogo)}" alt="STC CROP"><p class="quote-brand">${e(c.slogan)}</p></div><div class="quote-info"><h3>${e(c.name)}</h3><p>Hotline: ${e(c.phone)}</p><p>Văn phòng: ${e(c.office)}</p><p>${e(c.website)}</p>${partner}</div></header>`;}
const quoteTitle=q=>q.type==='gate'?'BÁO GIÁ ĐỘNG CƠ CỔNG TỰ ĐỘNG':'BÁO GIÁ THIẾT BỊ THÔNG MINH';
const quoteFoot=q=>`<footer class="quote-foot"><span>${esc(q.warranty)}</span><span>Cảm ơn Quý khách đã tin tưởng!</span></footer>`;
function quoteHTML(q,items=q.items,options={}){const c=q.company,t=totals(q),e=esc,opts=q.mode==='options',offset=options.offset||0;const price=i=>Number.isInteger(i.listPrice)&&i.listPrice>i.unitPrice?`<s class="old-price">${number(i.listPrice)}</s>${number(i.unitPrice)}`:number(i.unitPrice);const totalBlock=opts?`<div class="quote-choose">Quý khách chọn 01 trong ${q.items.length} phương án. Thành tiền từng dòng là giá riêng của phương án đó, không cộng dồn.${q.discount?` Chiết khấu ${number(q.discount)}% áp dụng trên phương án được chọn.`:''}</div>`:`${q.discount||q.vat!==''?`<div class="quote-subtotal"><span>Tổng hàng</span><span>${money(t.subtotal)}</span></div>`:''}${q.discount?`<div class="quote-subtotal"><span>Chiết khấu ${number(q.discount)}%</span><span>−${money(t.reduction)}</span></div>`:''}${q.vat!==''&&q.vat!=='included'?`<div class="quote-subtotal"><span>VAT ${e(q.vat)}%</span><span>${money(t.tax)}</span></div>`:''}<div class="quote-total"><span>TỔNG CỘNG</span><strong>${number(t.total)} đồng</strong></div>`;const appendix=q.type==='gate'&&!options.noAppendix&&!options.continued?gateAppendixHTML(q,e):'';return `<article class="quote">${quoteHead(q)}<div class="quote-body"><h2 class="quote-title">${quoteTitle(q)}</h2><div class="quote-meta"><span>${e(q.number)}</span><span>Ngày ${e(q.date.split('-').reverse().join('/'))}${options.page?` · Trang ${options.page}`:''}</span></div>${q.customer||q.address||q.phone?`<div class="quote-customer">${q.customer?`<b>Khách hàng:</b> ${e(q.customer)}<br>`:''}${q.phone?`<b>Điện thoại:</b> ${e(q.phone)}<br>`:''}${q.address?`<b>Công trình:</b> ${e(q.address)}`:''}</div>`:''}${q.promo&&!offset?`<div class="quote-promo"><b>ƯU ĐÃI</b>${e(q.promo)}</div>`:''}<table><thead><tr><th>Hạng mục</th><th>SL / Quy cách</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>${items.map((i,n)=>`<tr><td>${opts?`<span class="opt-tag">Phương án ${offset+n+1}</span>`:''}${e(i.name)}</td><td>${number(i.quantity)} ${e(i.unit)}</td><td>${price(i)}</td><td>${number(roundProduct(i.quantity,i.unitPrice))}</td></tr>`).join('')||'<tr><td colspan="4">Chọn sản phẩm để lập báo giá.</td></tr>'}</tbody></table>${options.continued?'<p class="quote-continuation">Tiếp theo ở trang sau.</p>':`${totalBlock}<div class="quote-bank"><b>THÔNG TIN THANH TOÁN</b><br>${e(c.bank)} · STK: <b>${e(c.accountNumber)}</b></div><div class="quote-note">${e([q.vat==='included'?'Đơn giá đã bao gồm VAT; không cộng thêm thuế.':q.vat===''?'VAT: chưa xác định.':'',q.validity?'Hiệu lực: '+q.validity:'',q.preparedBy?'Người lập: '+q.preparedBy:'',q.note].filter(Boolean).join('\n'))}</div>${appendix}`}</div>${quoteFoot(q)}</article>`;}
function appendixPageHTML(q,part,page){return `<article class="quote">${quoteHead(q)}<div class="quote-body"><h2 class="quote-title">${quoteTitle(q)}</h2><div class="quote-meta"><span>${esc(q.number)}</span><span>Phụ lục kỹ thuật · Trang ${page}</span></div>${gateAppendixHTML(q,esc,part)}</div>${quoteFoot(q)}</article>`;}
function renderPreview(){try{const t=totals(state);$('#liveTotal').textContent=state.mode==='options'?state.items.length+' phương án (không cộng)':money(t.total);$('#quotePreview').innerHTML=quoteHTML(state);$('#vatHint').textContent=state.vat==='included'?'Đơn giá đã bao gồm VAT; tổng tiền không cộng thêm thuế.':state.vat===''?'VAT chưa xác định; tổng hiện tại chưa cộng VAT.':`Đã tính VAT ${state.vat}% theo lựa chọn.`;$('#previewCount').textContent=state.items.length+' hạng mục';}catch(e){$('#liveTotal').textContent='Kiểm tra dữ liệu';}}
const FIELD_DEFAULTS={type:'smart',mode:'sum'};
function renderInputs(){$$('[data-field]').forEach(el=>el.value=state[el.dataset.field]??FIELD_DEFAULTS[el.dataset.field]??'');renderLines();renderProducts();renderPreview();inventory?.refresh();cloud?.render();}
function changed(){persist();renderPreview();inventory?.refresh();cloud?.render();}
let productLimit=30;
function pickerFilters(){return Object.fromEntries($$('[data-product-filter]').map(el=>[el.dataset.productFilter,el.value]));}
function setupPicker(){const host=$('.product-picker');const box=document.createElement('div');box.className='variant-filters';const fields=[['group','Nhóm sản phẩm',groups],['family','Dòng sản phẩm',['Leto','Athena','Hera']],['shape','Kiểu mặt',['Vuông','Chữ nhật']],['color','Màu sắc',['Trắng','Đen','Champagne','Stone gray','Rose gold']],['buttons','Số nút',['1','2','3','4','5','6']],['power','Công suất',['Công suất cao']],['radio','Kết nối ghi trong tên',['Wi-Fi','Bluetooth Mesh','Zigbee']]];box.innerHTML=fields.map(([key,label,options])=>`<label>${label}<select data-product-filter="${key}"><option value="">Tất cả</option>${options.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></label>`).join('');const advanced=document.createElement('details');advanced.className='advanced-picker';advanced.innerHTML='<summary>Lọc theo nhóm, dòng sản phẩm & biến thể</summary>';advanced.append(box);host.insertBefore(advanced,$('#productResults'));box.onchange=()=>{productLimit=30;renderProducts();};const tools=document.createElement('div');tools.className='picker-tools';tools.innerHTML='<label>Số lượng thêm<input id="pickerQty" type="number" min="0.0001" max="1000000" step="0.0001" value="1"></label><label class="smart-toggle"><input type="checkbox" id="preferStock"> Thông minh: ưu tiên hàng còn tồn</label><button id="clearFilters" type="button">Xóa bộ lọc</button><span id="productMatchCount" class="muted" role="status"></span>';host.insertBefore(tools,$('#productResults'));{let on=true;try{on=localStorage.getItem('stc-prefer-stock')!=='off';}catch(e){}$('#preferStock').checked=on;$('#preferStock').onchange=ev=>{try{localStorage.setItem('stc-prefer-stock',ev.target.checked?'on':'off');}catch(e){}productLimit=30;renderProducts();};}$('#clearFilters').onclick=()=>{$$('[data-product-filter]').forEach(s=>s.value='');$('#productSearch').value='';productLimit=30;renderProducts();};setupCatalogLoader(host);$('#productSearch').placeholder='Ví dụ: leto vuong den 3 nut, athena csc, mã hàng…';$('#productSearch').onkeydown=ev=>{if(ev.key==='Enter'){ev.preventDefault();$('#productResults [data-add]')?.click();}};}
function renderProducts(){if(!$('#productMatchCount'))return;const locked=inventory?.isLocked(state.id);const stocks=cloud?.stock()||inventory?.snapshot().rows||[];const prefer=$('#preferStock')?.checked;const used=id=>locked||cloud?.locked()?0:state.items.reduce((n,i)=>n+(i.productId===id&&!i.nonStock?i.quantity:0),0);const avail=p=>{const s=stocks.find(s=>s.id===p.id&&s.unit===p.unit);return s?s.quantity-used(p.id):null;};let matches=searchProducts(catalog,$('#productSearch').value,pickerFilters());if(prefer)matches=matches.map((p,n)=>({p,n,a:avail(p)})).sort((x,y)=>((y.a>0)-(x.a>0))||x.n-y.n).map(x=>x.p);const pickQty=Number($('#pickerQty')?.value)||1;
 $('#pickerCatalogStatus').textContent=`Danh mục hiện có ${catalog.length} mã.`+(catalog.length<=7?' Bạn đang dùng danh mục mẫu; chọn file NXT để nạp thiết bị thực tế.':' Tìm tên không dấu hoặc mã, nhập số lượng rồi bấm + Thêm.');
 $('#pickerLocked').hidden=!locked;
 $('#pickerCatalogStatus').textContent+=' Tồn khởi tạo theo NXT cuối kỳ 30/09/2026; các phát sinh trên máy được giữ lại.';$('#pickerAdded').textContent=`Đã chọn ${state.items.length} dòng thiết bị · Xem danh sách ↓`;
 $('#productMatchCount').textContent=`${matches.length} kết quả · hiển thị ${Math.min(productLimit,matches.length)}`;
 $('#productResults').innerHTML=matches.slice(0,productLimit).map(p=>{const v=variants(p),stock=stocks.find(s=>s.id===p.id);return `<article class="product-result"><strong>${esc(p.name)}</strong><span>${esc(p.id)} · ${esc(p.unit)} · <b>${money(p.unitPrice)}</b></span><small>${/^STC-/.test(p.id)?'Mã mẫu — cần chọn mã / biến thể thực tế':'Giá danh mục sau VAT'}</small><small>${esc([v.family,v.shape,v.color,v.buttons?v.buttons+' nút':'',v.power].filter(Boolean).join(' · '))}</small><span class="${stock?.quantity===0?'stock-danger':prefer&&avail(p)>0?'stock-ok':'muted'}">${stock?(prefer&&avail(p)>0?'✓ Còn ':'Tồn ')+number(stock.quantity)+' '+esc(stock.unit)+(used(p.id)?' · đã chọn '+number(used(p.id)):''):'Chưa có số tồn'}</span>${prefer&&stock&&avail(p)<pickQty?(()=>{const alt=stockSuggestions({productId:p.id,unit:p.unit,quantity:pickQty,unitPrice:p.unitPrice},-1,state.items,catalog,stocks);return alt.length?`<div class="stock-alt"><b>Gợi ý cùng loại còn tồn:</b>${alt.map(a=>`<button type="button" data-add="${esc(a.id)}" ${locked?'disabled':''}>+ ${esc(a.name)} · ${money(a.unitPrice)}</button>`).join('')}</div>`:'';})():''}<button type="button" class="primary" data-add="${esc(p.id)}" ${locked?'disabled':''}>+ Thêm vào báo giá</button></article>`;}).join('')||'<div class="empty"><b>Chưa tìm thấy thiết bị phù hợp</b><p>Thử tên ngắn hơn hoặc bấm Xóa bộ lọc. Nếu mới có 9 mã mẫu, hãy nạp file danh mục ngay phía trên.</p><button type="button" id="emptyClear">Xóa bộ lọc</button></div>';
 if(matches.length>productLimit)$('#productResults').insertAdjacentHTML('beforeend','<button id="moreProducts" type="button">Xem thêm 30 sản phẩm</button>');
}
function setupCatalogLoader(host){
 const loader=document.createElement('div');loader.className='picker-onboarding';loader.innerHTML='<p id="pickerCatalogStatus" class="muted"></p><label class="upload">Nạp danh mục từ Excel / JSON<input id="pickerCatalogFile" type="file" accept=".xlsx,.json"></label><p class="muted">Chọn NXT TH09.26.xlsx: cập nhật mã và giá niêm yết sau VAT vào danh mục. Việc nạp danh mục không cập nhật hay trừ tồn kho.</p><p id="pickerLoadStatus" role="status"></p><div id="pickerLocked" hidden><p>Báo giá này đã chốt nên không thể thêm thiết bị.</p><button type="button" id="copyForEditing">Nhân bản để thêm thiết bị</button></div><button type="button" id="pickerAdded"></button><p id="pickerAddStatus" role="status" aria-live="polite"></p>';
 host.prepend(loader);
 $('#pickerAdded').onclick=()=>$('#lineItems').scrollIntoView({behavior:'smooth',block:'start'});
 $('#copyForEditing').onclick=()=>{state={...clone(state),id:crypto.randomUUID(),number:state.number+'-COPY-'+Date.now().toString().slice(-5),date:today()};renderInputs();changed();renderProducts();tell('Đã tạo bản nháp mới để thêm thiết bị. Phiếu cũ giữ nguyên.');};
 $('#pickerCatalogFile').onchange=async event=>{try{const f=event.target.files[0];if(!f)return;if(f.size>5*1024*1024)throw Error('File vượt 5 MB.');let rows,excluded=0;if(/\.json$/i.test(f.name)){const data=JSON.parse(await f.text());rows=normalizeProducts(Array.isArray(data)?data:data.products);}else{const book=XLSX.read(await f.arrayBuffer(),{type:'array',raw:true});if(!book.Sheets['NXT TH09.26'])throw Error('Chọn file NXT TH09.26.xlsx; với mẫu Excel khác hãy nhập ở tab Bảng giá.');const data=prepareNxt(XLSX.utils.sheet_to_json(book.Sheets['NXT TH09.26'],{header:1,defval:'',raw:true,range:0}));rows=normalizeProducts(data.products);excluded=data.issues.length;}
 if(!rows.length||rows.length>5000)throw Error('Danh mục cần 1–5.000 mã.');const incoming=rows.filter(p=>!catalog.some(c=>c.id===p.id));const previous=catalog;catalog=[...catalog.map(p=>rows.find(r=>r.id===p.id)||p),...incoming];persist();if(!storageOK){catalog=previous;throw Error('Chưa lưu được danh mục.');}$$('[data-product-filter]').forEach(el=>el.value='');$('#productSearch').value='';productLimit=30;applyGrossToDraft(rows);renderProducts();renderCatalog();inventory?.render();$('#pickerLoadStatus').textContent=`Đã thêm ${incoming.length} mã mới; đã cập nhật giá sau VAT của các mã có trong file.`+(excluded?` ${excluded} dòng nguồn chưa đủ điều kiện nhập, xem chi tiết ở tab Tồn kho.`:'')+' Bây giờ tìm thiết bị và bấm + Thêm.';}catch(err){$('#pickerLoadStatus').textContent=err.message;}finally{event.target.value='';}};
}

function applyGrossToDraft(products){if(inventory?.isLocked(state.id))return;let changedCount=0;state.items=state.items.map(i=>{const p=products.find(p=>p.id===i.productId);if(!p)return i;changedCount++;return {...i,name:p.name,unit:p.unit,unitPrice:p.unitPrice};});if(changedCount||!state.items.length)state.vat='included';renderInputs();changed();}
function mergeSameProducts(items){const result=[];for(const item of items){const old=item.productId&&!item.nonStock&&result.find(x=>x.productId===item.productId&&!x.nonStock&&x.unit===item.unit&&x.unitPrice===item.unitPrice);if(old&&old.quantity+item.quantity<=1000000)old.quantity=Math.round((old.quantity+item.quantity)*10000)/10000;else result.push({...item});}return result;}
async function migrateListPrices(){const key='stc-list-prices-v8';if(localStorage.getItem(key))return;const response=await fetch('assets/list-prices-v8.json',{cache:'no-store'});if(!response.ok)throw Error('Không tải được giá niêm yết sau VAT.');const data=await response.json(),prices=normalizeProducts(data.products);const map=new Map(prices.map(p=>[p.id,p]));const backup=localStorage.getItem(KEY);if(backup)localStorage.setItem('stc-before-list-prices-v8',backup);catalog=[...catalog.filter(p=>p.id!=='STC-008'&&!map.has(p.id)),...prices];if(!inventory?.isLocked(state.id)){state.items=mergeSameProducts(state.items.map(i=>{const p=map.get(i.productId==='STC-008'?'20038367':i.productId);return p?{...i,productId:p.id,name:p.name,unit:p.unit,unitPrice:p.unitPrice}:i;}));state.vat='included';}persist();if(!storageOK)throw Error('Chưa lưu được giá mới.');localStorage.setItem(key,'done');renderInputs();inventory?.render();tell('Đã cập nhật 207 mã theo giá sau VAT; gộp bộ trung tâm mẫu vào mã FPT.');}
async function migrateCurtain(){const key='stc-curtain-fpt-v2';if(localStorage.getItem(key))return;const r=await fetch('assets/curtain-fpt.json',{cache:'no-store'});if(!r.ok)throw Error('Không tải được bảng giá rèm FPT.');const d=await r.json();const products=normalizeProducts(d.products),drop=new Set([...d.removeIds,...Object.keys(d.mergeIds)]);const previous=catalog,before=catalog.length;catalog=[...catalog.filter(p=>!drop.has(p.id)&&!products.some(n=>n.id===p.id)),...products];if(!inventory?.isLocked(state.id)){state.items=mergeSameProducts(state.items.map(i=>{const to=d.mergeIds[i.productId],p=to&&catalog.find(c=>c.id===to);return p?{...i,productId:p.id,name:p.name,unit:p.unit,unitPrice:p.unitPrice}:i;}));}persist();if(!storageOK){catalog=previous;throw Error('Chưa lưu được danh mục rèm FPT.');}localStorage.setItem(key,'done');renderInputs();renderCatalog();tell('Đã bỏ '+(before-catalog.length+products.length)+' mã AOK/mẫu trùng; thêm động cơ + ray rèm kéo ngang theo giá FPT. Báo giá đã lưu giữ nguyên.');}
async function migrateGate(){const d=await loadGateData();const key='stc-gate-v2';if(localStorage.getItem(key))return;const incoming=d.products.filter(p=>!catalog.some(c=>c.id===p.id));if(incoming.length){const previous=catalog;catalog=[...catalog,...incoming];persist();if(!storageOK){catalog=previous;throw Error('Chưa lưu được danh mục động cơ cổng.');}}localStorage.setItem(key,'done');renderCatalog();renderProducts();if(incoming.length)tell('Đã thêm '+incoming.length+' mã động cơ cổng vào danh mục (tìm: cong, am san, dea, ab gate).');}
function chooseSku(index,id){if(inventory?.isLocked(state.id))return;const item=state.items[index],p=catalog.find(p=>p.id===id);if(!item)return;if(!p){item.productId='';renderLines();changed();return;}Object.assign(item,{productId:p.id,name:p.name,unit:p.unit,unitPrice:p.unitPrice,nonStock:false});renderLines();changed();tell('Đã lấy tên, đơn vị và giá danh mục theo mã '+p.id);}

function setupEntry(){
 const batch=document.createElement('details');batch.className='batch-entry';batch.innerHTML='<summary>Nhập nhanh nhiều thiết bị từ danh sách</summary><p>Mỗi dòng: Mã hàng | Số lượng | Đơn giá tùy chọn. Ví dụ: 20044135 | 8 | 2079k. Bỏ giá để lấy giá danh mục. Dùng đúng đơn vị của mã hàng.</p><textarea id="batchProducts" rows="5" placeholder="20044135 | 8 | 2079k&#10;20038367 | 1"></textarea><button type="button" id="addBatch">Kiểm tra & thêm danh sách</button><p id="batchError" class="error" role="status"></p>';$('.product-picker').append(batch);
 $('#addBatch').onclick=()=>{try{if(inventory?.isLocked(state.id))throw Error('Báo giá đã khóa.');const lines=$('#batchProducts').value.split(/\r?\n/).filter(x=>x.trim());if(!lines.length)throw Error('Nhập ít nhất một dòng.');if(lines.length+state.items.length>500)throw Error('Tối đa 500 dòng báo giá.');const incoming=lines.map((line,index)=>{const cells=line.split(/\t|\|/).map(x=>x.trim());if(cells.length<2||cells.length>3)throw Error('Dòng '+(index+1)+': dùng Mã | Số lượng | Giá.');const p=catalog.find(p=>p.id===cells[0]);if(!p)throw Error('Dòng '+(index+1)+': chưa có mã '+cells[0]);const quantity=Number(cells[1].replace(',','.'));const item={productId:p.id,name:p.name,unit:p.unit,quantity,unitPrice:cells[2]?parsePrice(cells[2]):p.unitPrice};checkQuote({...state,items:[item]});return item;});state.items=mergeSameProducts([...state.items,...incoming]);renderLines();changed();$('#batchProducts').value='';$('#batchError').textContent='Đã thêm '+incoming.length+' dòng theo đúng mã danh mục.';}catch(err){$('#batchError').textContent=err.message;}};
 const editor=document.createElement('section');editor.className='card';editor.innerHTML='<h2>Chỉnh tên và giá danh mục</h2><p>Đồng bộ tên hiển thị theo mã giữa danh mục và kho. Giá trên báo giá đã tạo giữ nguyên; dùng “Lấy tên & giá danh mục” để cập nhật từng dòng nháp.</p><div class="variant-filters"><label>Tìm trong danh mục<input id="catalogFind" placeholder="Tên không dấu hoặc mã hàng"></label><label>Mã hàng<select id="catalogEditId"></select></label><label>Tên chuẩn<input id="catalogEditName" maxlength="300"></label><label>Đơn giá (VND hoặc k)<input id="catalogEditPrice" placeholder="2079k hoặc 2.079.000"></label></div><button type="button" id="saveCatalogProduct">Lưu tên & giá</button><p id="catalogEditError" role="status" class="muted"></p>';$('#catalog').prepend(editor);
 function selected(){const p=catalog.find(p=>p.id===$('#catalogEditId').value);$('#catalogEditName').value=p?.name||'';$('#catalogEditPrice').value=p?.unitPrice??'';}
 window.refreshCatalogEditor=()=>{const selectedId=$('#catalogEditId').value;$('#catalogEditId').innerHTML=searchProducts(catalog,$('#catalogFind').value).map(p=>`<option value="${esc(p.id)}">${esc(p.id)} · ${esc(p.name)}</option>`).join('');if([...$('#catalogEditId').options].some(o=>o.value===selectedId))$('#catalogEditId').value=selectedId;selected();};$('#catalogFind').oninput=()=>window.refreshCatalogEditor();$('#catalogEditId').onchange=selected;
 $('#saveCatalogProduct').onclick=()=>{try{const id=$('#catalogEditId').value,old=catalog.find(p=>p.id===id);if(!old)throw Error('Chọn mã hàng.');const product=normalizeProducts([{...old,name:$('#catalogEditName').value,unitPrice:$('#catalogEditPrice').value}])[0];const previous=catalog;catalog=catalog.map(p=>p.id===id?product:p);persist();if(!storageOK){catalog=previous;throw Error('Chưa lưu được danh mục.');}renderCatalog();renderProducts();inventory?.render();$('#catalogEditError').textContent='Đã lưu tên và giá cho '+id+'. Đơn vị và số tồn giữ nguyên.';}catch(err){$('#catalogEditError').textContent=err.message;}};
 window.refreshCatalogEditor();
}
function renderLines(){$('#itemCount').textContent=state.items.length+' hạng mục';$('#lineItems').innerHTML=state.items.map((i,n)=>`<div class="line-item" data-index="${n}"><div class="line-top"><input class="check" type="checkbox" aria-label="Chọn ${esc(i.name)}"><input data-item="name" value="${esc(i.name)}" maxlength="300" aria-label="Tên sản phẩm ${n+1}"><button class="icon-button" data-remove="${n}" aria-label="Xóa ${esc(i.name)}">×</button></div><div class="line-fields"><label>Số lượng<input data-item="quantity" value="${i.quantity}" type="number" min="0.0001" max="1000000" step="0.0001"></label><label>Đơn vị<input data-item="unit" value="${esc(i.unit)}" maxlength="30"></label><label>Đơn giá (đ)<input data-item="unitPrice" value="${i.unitPrice}" type="number" min="0" max="100000000000" step="1"></label><label>Giá gốc gạch ngang (tùy chọn)<input data-item="listPrice" value="${i.listPrice??''}" type="number" min="0" max="100000000000" step="1" placeholder="Để trống nếu không giảm"></label><div class="line-amount">${money(roundProduct(i.quantity,i.unitPrice))}</div>${i.productId?`<button type="button" data-sync="${n}">Lấy tên & giá danh mục</button>`:""}</div></div>`).join('')||'<div class="empty">Chọn sản phẩm phía trên hoặc nạp báo giá mẫu để bắt đầu.</div>';}
function renderCatalog(){window.refreshCatalogEditor?.();$('#catalogRows').innerHTML=catalog.map(p=>`<tr><td>${esc(p.id)}</td><td>${esc(p.name)}</td><td>${esc(p.unit)}</td><td>${money(p.unitPrice)}</td></tr>`).join('');$('#catalogSource').textContent=`${catalog.length} sản phẩm · Giá do bạn cung cấp, có thể điều chỉnh trong từng báo giá.`;}
function renderSaved(){$('#savedList').innerHTML=saved.map(q=>`<article class="saved-card"><div><h2>${esc(q.customer||'Chưa có tên khách')}</h2><p class="muted">${esc(q.number)} · ${esc(q.date)} · ${q.items.length} hạng mục · ${inventory?.receipt(q.id)?(inventory.receipt(q.id).status==='issued'?'Đã chốt / xuất kho':'Đã hủy / hoàn kho'):'Nháp'}</p><strong>${q.mode==='options'?q.items.length+' phương án':money(totals(q).total)}</strong></div><div class="heading-actions"><button data-open="${esc(q.id)}">Mở</button><button data-copy="${esc(q.id)}">Nhân bản</button><button data-delete="${esc(q.id)}">Xóa</button></div></article>`).join('')||'<div class="empty">Chưa có báo giá đã lưu. Bấm “Lưu báo giá” sau khi soạn.</div>';}
const companyLabels={name:'Tên công ty',slogan:'Slogan',phone:'Hotline',office:'Địa chỉ văn phòng',website:'Website',email:'Email',bank:'Ngân hàng',accountNumber:'Số tài khoản'};
function renderCompany(){$('#companyFields').innerHTML=Object.entries(companyLabels).map(([k,l])=>`<label class="${['name','slogan','office'].includes(k)?'wide':''}">${l}<input data-company="${k}" value="${esc(company[k])}" maxlength="250"></label>`).join('');}
function download(blob,name){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
const fileName=()=>state.number.replace(/[^\p{L}\p{N}_-]/gu,'-');
function bind(){
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$$('[data-field]').forEach(el=>el.addEventListener('input',()=>{const k=el.dataset.field;let v=el.value;if(k==='discount'){v=Number(v);if(v<0||v>100)return;}state[k]=v;changed();}));
setupPicker();setupEntry();$('#productSearch').oninput=()=>{productLimit=30;renderProducts();};
$('#productResults').onclick=e=>{if(e.target.closest('#emptyClear')){$('#clearFilters').click();return;}if(e.target.closest('#moreProducts')){productLimit+=30;renderProducts();return;}const b=e.target.closest('[data-add]');if(!b)return;if(inventory?.isLocked(state.id))return tell('Báo giá đã chốt. Bấm Nhân bản để thêm thiết bị.');const quantity=Number($('#pickerQty').value);if(!$('#pickerQty').checkValidity()||!Number.isFinite(quantity)||quantity<=0)return tell('Nhập số lượng hợp lệ.');const p=catalog.find(p=>p.id===b.dataset.add);if(state.items.length>=500)return tell('Báo giá tối đa 500 dòng.');state.items=mergeSameProducts([...state.items,{productId:p.id,name:p.name,unit:p.unit,unitPrice:p.unitPrice,quantity}]);renderLines();changed();renderProducts();$('#pickerAddStatus').textContent=`✓ Đã thêm ${number(quantity)} ${p.unit} · ${p.name}`;const stock=inventory?.snapshot().rows.find(r=>r.id===p.id);const needed=state.items.filter(i=>i.productId===p.id&&!i.nonStock).reduce((n,i)=>n+i.quantity,0);if(!stock||stock.quantity<needed){$('#pickerAddStatus').textContent+=' ⚠ '+(!stock?'Chưa xác minh tồn.':'Không đủ tồn: cần '+number(needed)+', còn '+number(stock.quantity))+'. Xem cảnh báo và gợi ý tại Chốt đơn & xuất kho.';}tell('Đã thêm '+p.name+' vào báo giá.');};
$('#lineItems').oninput=e=>{const k=e.target.dataset.item;if(!k)return;const row=e.target.closest('[data-index]'),i=state.items[Number(row.dataset.index)];let v=e.target.value;if(k==='listPrice'){if(v===''){delete i.listPrice;e.target.setCustomValidity('');changed();return;}v=Number(v);if(!Number.isInteger(v)||v<0||v>100000000000){e.target.setCustomValidity('Giá gốc là số nguyên đồng.');return;}e.target.setCustomValidity('');i.listPrice=v;changed();return;}if(k==='quantity'||k==='unitPrice'){v=Number(v);if(!Number.isFinite(v)||v<0||v>100000000000)return;if(k==='quantity'&&(v<=0||v>1000000||String(v).includes('e')||(String(v).split('.')[1]||'').length>4)){e.target.setCustomValidity('Số lượng dương, tối đa 4 chữ số thập phân.');return;}if(k==='unitPrice'&&!Number.isInteger(v)){e.target.setCustomValidity('Giá phải là số nguyên đồng.');return;}}e.target.setCustomValidity('');i[k]=v;row.querySelector('.line-amount').textContent=money(roundProduct(i.quantity,i.unitPrice));changed();};
$('#lineItems').onclick=e=>{const sync=e.target.closest('[data-sync]');if(sync){chooseSku(Number(sync.dataset.sync),state.items[Number(sync.dataset.sync)].productId);return;}const b=e.target.closest('[data-remove]');if(b){state.items.splice(Number(b.dataset.remove),1);renderLines();changed();}};
$('#addManual').onclick=()=>{state.items.push({productId:'',name:'Sản phẩm mới',unit:'cái',quantity:1,unitPrice:0});renderLines();changed();};
$('#loadSample').onclick=async()=>{if(state.items.length&&!await confirmAction('Nạp báo giá mẫu?','Thay các hạng mục đang soạn bằng 7 sản phẩm mẫu, tổng 88.514.000đ.'))return;state.items=clone(sample.items);Object.assign(state,{type:'smart',mode:'sum',promo:''});state.discount=0;state.vat='';state.warranty=sample.warrantyText;renderInputs();changed();};
$('#loadGate').onclick=async()=>{try{if(inventory?.isLocked(state.id))throw Error('Báo giá đã chốt. Bấm Tạo mới hoặc Nhân bản trước.');if(state.items.length&&!await confirmAction('Nạp mẫu động cơ cổng?','Thay các hạng mục đang soạn bằng 3 phương án động cơ cổng (AB GATE âm sàn, DEA Ghost 100 âm sàn, DEA Livi lùa) kèm ưu đãi, điều khoản và phụ lục kỹ thuật.'))return;const s=gateSample(catalog);Object.assign(state,s,{type:'gate',mode:'options',discount:0,vat:'included'});renderInputs();changed();tell('Đã nạp 3 phương án động cơ cổng. Kiểm tra ưu đãi và hiệu lực trước khi gửi khách.');}catch(err){tell(err.message);}};
$('#newQuote').onclick=async()=>{if(state.items.length&&!await confirmAction('Tạo báo giá mới?','Bản nháp hiện tại sẽ được thay thế. Hãy lưu nếu bạn muốn giữ lại.'))return;state=fresh();renderInputs();changed();};
$('#saveQuote').onclick=()=>{try{checkQuote(state);if(!state.items.length)throw Error('Thêm ít nhất một sản phẩm trước khi lưu.');const q=clone(state);q.updatedAt=new Date().toISOString();const i=saved.findIndex(s=>s.id===q.id);if(i>=0)saved[i]=q;else saved.unshift(q);persist();if(storageOK)tell('Đã lưu báo giá '+q.number);}catch(e){tell(e.message);}};
$('#adjustPrices').onclick=async()=>{const ids=$$('.line-item').filter(r=>r.querySelector('.check').checked).map(r=>Number(r.dataset.index));if(!ids.length)return tell('Đánh dấu các dòng cần điều chỉnh giá trước.');const pct=Number($('#adjustPercent').value);if(!Number.isFinite(pct)||pct< -100||pct>1000)return tell('Mức điều chỉnh từ -100% đến 1000%.');if(!await confirmAction('Điều chỉnh đơn giá?',`${ids.length} hạng mục sẽ ${pct>=0?'tăng':'giảm'} ${Math.abs(pct)}%. Chỉ áp dụng một lần vào giá hiện tại.`))return;ids.forEach(i=>state.items[i].unitPrice=Math.round(state.items[i].unitPrice*(1+pct/100)));renderLines();changed();};
$('#savedList').onclick=async e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.open||b.dataset.copy||b.dataset.delete;const q=saved.find(s=>s.id===id);if(!q)return;if(b.dataset.delete){if(inventory?.isLocked(id)){tell('Báo giá đã có phiếu xuất cần giữ để đối chiếu.');return;}if(await confirmAction('Xóa báo giá?','Báo giá này sẽ bị xóa khỏi danh sách trên thiết bị.')){saved=saved.filter(s=>s.id!==id);persist();renderSaved();}return;}if(state.items.length&&!await confirmAction('Mở báo giá đã lưu?','Thay bản nháp đang soạn. Bản đã lưu vẫn được giữ trong danh sách.'))return;state=clone(q);if(b.dataset.copy){state.id=crypto.randomUUID();state.number+='-COPY';state.date=today();}renderInputs();changed();showView('editor');};
$('#companyFields').oninput=e=>{if(e.target.dataset.company){company[e.target.dataset.company]=e.target.value;persist();}};
$('#applyCompany').onclick=()=>{state.company=clone(company);changed();tell('Đã cập nhật thông tin công ty vào bản đang soạn.');};
$('#resetLogo').onclick=()=>{company.logo='assets/stc-logo.jpg';delete company.fptLogo;persist();tell('Đã khôi phục logo. Bấm Áp dụng để cập nhật bản đang soạn.');};
for(const [id,key] of [['stcLogo','logo'],['fptLogo','fptLogo']])$('#'+id).onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>1000000||!['image/png','image/jpeg','image/webp'].includes(file.type))return tell('Chọn ảnh PNG/JPG/WebP dưới 1 MB.');const r=new FileReader();r.onload=()=>{company[key]=r.result;persist();tell('Đã lưu logo. Bấm Áp dụng để cập nhật bản đang soạn.');};r.readAsDataURL(file);};
$('#backup').onclick=()=>download(new Blob([JSON.stringify({schemaVersion:1,company,catalog,state,saved,inventory:inventory?.snapshot()},null,2)],{type:'application/json'}),'STC-sao-luu-'+today()+'.json');
}
async function start(){try{[sample,catalog]=await Promise.all([fetch('assets/sample.json').then(r=>r.json()),fetch('assets/prices.json').then(r=>r.json()).then(d=>d.products)]);company={...sample.company,logo:'assets/stc-logo.jpg'};state=fresh();try{const data=JSON.parse(localStorage.getItem(KEY));if(data?.schemaVersion===1){checkQuote(data.state);data.saved.forEach(checkQuote);catalog=normalizeProducts(data.catalog);state=data.state;company=data.company;saved=data.saved;}}catch(e){tell('Không đọc được bản lưu cũ; đang mở dữ liệu mẫu.');}bind();renderInputs();setupImportExport();inventory=installInventory({chooseSku,productsChanged:renderProducts,addCatalog:async products=>{const incoming=normalizeProducts(products);for(const p of incoming){const old=catalog.find(c=>c.id===p.id);if(old&&old.unit!==p.unit)throw Error("Đơn vị danh mục không khớp mã "+p.id);}const next=[...catalog.map(p=>{const found=incoming.find(x=>x.id===p.id);return found?{...p,name:found.name,unitPrice:found.unitPrice}:p;}),...incoming.filter(p=>!catalog.some(c=>c.id===p.id))];const previous=catalog;catalog=next;persist();if(!storageOK){catalog=previous;throw Error("Không lưu được danh mục; chưa nhập kho.");}applyGrossToDraft(incoming);renderCatalog();renderProducts();},esc,state:()=>state,catalog:()=>catalog,tell,confirm:confirmAction,changed,showView,renderCanvas,open:q=>{state=q;renderInputs();changed();showView('editor');},recover:receipts=>{for(const r of receipts){const idx=saved.findIndex(q=>q.id===r.quoteId);if(idx<0)saved.unshift(clone(r.quote));else saved[idx]=clone(r.quote);if(state.id===r.quoteId)state=clone(r.quote);}renderInputs();persist();}});cloud=installCloud({state:()=>state,clone,totals,amount:i=>roundProduct(i.quantity,i.unitPrice),number,money,esc,fold,confirm:confirmAction,tell,changed,saveLocal:()=>{const q=clone(state);q.updatedAt=new Date().toISOString();const i=saved.findIndex(s=>s.id===q.id);if(i>=0)saved[i]=q;else saved.unshift(q);persist();},stockChanged:()=>renderProducts(),open:q=>{state=q;renderInputs();changed();showView('editor');}});await migrateListPrices();await migrateCurtain();await migrateGate();await inventory.seedSource();inventory.refresh();renderProducts();}catch(e){tell('Không thể tải ứng dụng: '+e.message);}}
start();
function setupImportExport(){
  $$('.downloads button').forEach(b=>b.onclick=()=>exportQuote(b.dataset.export));
  $('#priceFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('File vượt 5 MB.');if(file.name.toLowerCase().endsWith('.json')){const data=JSON.parse(await file.text());importRows=normalizeProducts(Array.isArray(data)?data:data.products);importBook=null;showImportReview();}else{importBook=XLSX.read(await file.arrayBuffer(),{type:'array',raw:true,cellFormula:false});showMapping();}}catch(e){tell(e.message);}finally{e.target.value='';}};
  $('#resetCatalog').onclick=async()=>{if(await confirmAction('Khôi phục bảng giá mẫu?','Thay danh mục hiện tại bằng 7 sản phẩm mẫu. Giá trên báo giá đang soạn và đã lưu không thay đổi.')){catalog=normalizeProducts((await fetch('assets/prices.json').then(r=>r.json())).products);persist();renderCatalog();renderProducts();tell('Đã khôi phục danh mục mẫu.');}};
  $('#templateDownload').onclick=()=>{const wb=XLSX.utils.book_new();const sheet=XLSX.utils.aoa_to_sheet([['Mã','Tên sản phẩm','Đơn vị','Đơn giá'],...catalog.map(p=>[p.id,p.name,p.unit,p.unitPrice])]);sheet['!cols']=[{wch:18},{wch:42},{wch:12},{wch:20}];XLSX.utils.book_append_sheet(wb,sheet,'Bang gia');XLSX.writeFile(wb,'STC-bang-gia-mau.xlsx');};
  $('#restore').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>10*1024*1024)throw Error('Bản sao lưu vượt 10 MB.');const d=JSON.parse(await f.text());if(d.schemaVersion!==1||!Array.isArray(d.saved)||!d.company||typeof d.company.accountNumber!=='string')throw Error('File sao lưu không đúng định dạng STC.');checkQuote(d.state);d.saved.forEach(checkQuote);const validated=normalizeProducts(d.catalog);if(d.inventory)inventory.validate(d.inventory);else if(inventory.hasTransactions())throw Error('Bản sao lưu này thiếu dữ liệu kho. Không thay thế khi đã có giao dịch kho.');if(await confirmAction('Khôi phục bản sao lưu?',`Thay dữ liệu trên thiết bị bằng ${d.saved.length} báo giá và ${validated.length} sản phẩm trong file.`)){if(d.inventory)await inventory.restore(d.inventory);company=d.company;catalog=validated;state=d.state;saved=d.saved;if(d.inventory){for(const r of d.inventory.receipts){const idx=saved.findIndex(q=>q.id===r.quoteId);if(idx<0)saved.unshift(clone(r.quote));else saved[idx]=clone(r.quote);if(state.id===r.quoteId)state=clone(r.quote);}}persist();renderInputs();renderSaved();tell('Đã khôi phục dữ liệu.');}}catch(e){tell(e.message);}finally{e.target.value='';}};
  const context=document.modelContext;
  if(context?.registerTool){try{context.registerTool({name:'get_quote_summary',description:'Read the current STC quotation totals and product lines without changing data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({number:state.number,items:clone(state.items),...totals(state),vat:state.vat})});}catch(e){/* Optional browser capability. */}}
}
function showMapping(){const panel=$('#importPanel');panel.hidden=false;panel.innerHTML=`<div class="import-box"><h2>Chọn sheet và cột dữ liệu</h2><label>Sheet<select id="sheetSelect">${importBook.SheetNames.map(s=>`<option>${esc(s)}</option>`).join('')}</select></label><div id="columnMapping" class="mapping"></div><p class="muted">Dòng đầu tiên là tiêu đề. Chọn đúng các cột trước khi nhập.</p><button id="previewImport" class="primary">Kiểm tra dữ liệu</button><p id="importError" class="error"></p></div>`;$('#sheetSelect').onchange=mapColumns;$('#previewImport').onclick=()=>{try{const rows=XLSX.utils.sheet_to_json(importBook.Sheets[$('#sheetSelect').value],{header:1,defval:'',raw:true});const indexes=Object.fromEntries($$('[data-map]').map(s=>[s.dataset.map,Number(s.value)]));if(new Set(Object.values(indexes)).size!==4)throw Error('Mỗi trường cần một cột khác nhau.');importRows=normalizeProducts(rows.slice(1).filter(r=>r.some(x=>x!=='')).map(r=>Object.fromEntries(Object.entries(indexes).map(([k,i])=>[k,r[i]]))));showImportReview();}catch(e){$('#importError').textContent=e.message;}};mapColumns();}
function mapColumns(){const rows=XLSX.utils.sheet_to_json(importBook.Sheets[$('#sheetSelect').value],{header:1,defval:'',raw:true});const headers=rows[0]||[];const fields=[['id','Mã sản phẩm',/mã|sku|^id$|code/i],['name','Tên sản phẩm',/tên|name|sản phẩm/i],['unit','Đơn vị',/đơn vị|unit|đvt/i],['unitPrice','Đơn giá',/đơn giá|price|giá bán/i]];$('#columnMapping').innerHTML=fields.map(([k,l,re],i)=>{let found=headers.findIndex(h=>re.test(String(h)));if(found<0)found=i;return `<label>${l}<select data-map="${k}">${headers.map((h,n)=>`<option value="${n}" ${n===found?'selected':''}>${esc(h||'Cột '+(n+1))}</option>`).join('')}</select></label>`;}).join('');}
function showImportReview(){if(!importRows?.length||importRows.length>5000)throw Error('Bảng giá cần từ 1 đến 5.000 sản phẩm.');const panel=$('#importPanel');panel.hidden=false;panel.innerHTML=`<div class="import-box"><h2>${importRows.length} sản phẩm hợp lệ</h2><p class="muted">${importRows.filter(p=>catalog.some(c=>c.id===p.id)).length} mã trùng danh mục hiện tại. Khi gộp, giá và tên mới sẽ thay thông tin của mã trùng.</p><div class="table-scroll"><table class="data-table"><thead><tr><th>Mã</th><th>Tên</th><th>Giá</th></tr></thead><tbody>${importRows.slice(0,8).map(p=>`<tr><td>${esc(p.id)}</td><td>${esc(p.name)}</td><td>${money(p.unitPrice)}</td></tr>`).join('')}</tbody></table></div><div class="heading-actions"><button id="mergeImport" class="primary">Gộp theo mã</button><button id="replaceImport">Thay toàn bộ</button><button id="cancelImport">Hủy</button></div></div>`;$('#cancelImport').onclick=()=>panel.hidden=true;$('#mergeImport').onclick=()=>applyImport(false);$('#replaceImport').onclick=()=>applyImport(true);}
async function applyImport(replace){if(!await confirmAction(replace?'Thay toàn bộ bảng giá?':'Gộp bảng giá?',replace?`Danh mục sẽ còn ${importRows.length} sản phẩm từ file này.`:'Mã trùng sẽ lấy thông tin mới; mã chưa có sẽ được thêm. Giá trên các báo giá đã tạo không thay đổi.'))return;if(replace)catalog=clone(importRows);else{const map=new Map(catalog.map(p=>[p.id,p]));importRows.forEach(p=>map.set(p.id,p));catalog=[...map.values()];}persist();renderCatalog();renderProducts();$('#importPanel').hidden=true;tell('Đã cập nhật bảng giá.');}
async function exportQuote(type){if(busy)return;try{checkQuote(state);if(!state.items.length)throw Error('Thêm sản phẩm trước khi tải báo giá.');const invalid=$$('input').find(i=>!i.checkValidity());if(invalid){invalid.reportValidity();throw Error('Kiểm tra các ô nhập trước khi xuất.');}busy=true;$$('[data-export]').forEach(b=>b.disabled=true);tell('Đang tạo '+type.toUpperCase()+'…');const q=clone(state);if(type==='xlsx')exportExcel(q);else await exportVisual(q,type);tell('Đã tạo file '+type.toUpperCase()+'. Kiểm tra mục tải xuống của trình duyệt.');}catch(e){tell('Chưa xuất được: '+e.message);}finally{busy=false;$$('[data-export]').forEach(b=>b.disabled=false);$('#exportRoot').innerHTML='';}}
function exportExcel(q){const c=q.company,t=totals(q);const opts=q.mode==='options';const rows=[[c.name],['Hotline',c.phone],['Văn phòng',c.office],['Website',c.website],[quoteTitle(q)],['Số báo giá',q.number,'Ngày',q.date],['Khách hàng',q.customer],['Điện thoại',q.phone],['Công trình',q.address],['Hạng mục','Đơn vị','Số lượng','Đơn giá','Thành tiền']];const first=11;q.items.forEach((i,n)=>rows.push([i.name,i.unit,i.quantity,i.unitPrice,{t:'n',f:`ROUND(C${first+n}*D${first+n},0)`,v:roundProduct(i.quantity,i.unitPrice)}]));if(opts){q.items.forEach((i,n)=>{rows[first-1+n][0]='Phương án '+(n+1)+': '+i.name;});const last=rows.length;rows.push(['Quý khách chọn 01 trong '+q.items.length+' phương án. Thành tiền từng dòng là giá riêng của phương án đó, không cộng dồn.']);if(q.promo)rows.push(['Ưu đãi',q.promo]);rows.push(['Ngân hàng',c.bank],['Số tài khoản',{t:'s',v:c.accountNumber,z:'@'}],['Bảo hành',q.warranty],['Hiệu lực',q.validity],['Người lập',q.preparedBy],['Ghi chú',q.note],[c.slogan]);const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:60},{wch:23},{wch:15},{wch:19},{wch:23}];ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:4}},{s:{r:4,c:0},e:{r:4,c:4}},{s:{r:last,c:0},e:{r:last,c:4}}];for(let r=first;r<first+q.items.length;r++){for(const col of ['D','E'])ws[col+r].z='#,##0';}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Bao gia');wb.Workbook={CalcPr:{calcMode:'auto',fullCalcOnLoad:true}};XLSX.writeFile(wb,fileName()+'.xlsx');return;}
const sub=rows.length+1;rows.push(['Tổng hàng','','','',{t:'n',f:`SUM(E${first}:E${sub-1})`,v:t.subtotal}]);const disc=rows.length+1;rows.push(['Chiết khấu (%)',q.discount,'','',{t:'n',f:`ROUND(E${sub}*B${disc}/100,0)`,v:t.reduction}]);const vat=rows.length+1;rows.push([q.vat==='included'?'Đơn giá đã gồm VAT':q.vat===''?'VAT chưa xác định':'VAT (%)',(q.vat===''||q.vat==='included')?'':Number(q.vat),'','',{t:'n',f:(q.vat===''||q.vat==='included')?'0':`ROUND((E${sub}-E${disc})*B${vat}/100,0)`,v:t.tax}]);rows.push(['TỔNG CỘNG','','','',{t:'n',f:`E${sub}-E${disc}+E${vat}`,v:t.total}]);rows.push(['Ngân hàng',c.bank],['Số tài khoản',{t:'s',v:c.accountNumber,z:'@'}],['Bảo hành',q.warranty],['Hiệu lực',q.validity],['Người lập',q.preparedBy],['Ghi chú',q.note],[c.slogan]);const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:43},{wch:23},{wch:15},{wch:19},{wch:23}];ws['!merges']=[{s:{r:0,c:0},e:{r:0,c:4}},{s:{r:4,c:0},e:{r:4,c:4}}];for(let r=first;r<sub;r++){for(const col of ['D','E'])ws[col+r].z='#,##0';}for(let r=sub;r<=vat+1;r++)ws['E'+r].z='#,##0';const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Bao gia');wb.Workbook={CalcPr:{calcMode:'auto',fullCalcOnLoad:true}};XLSX.writeFile(wb,fileName()+'.xlsx');}
async function renderCanvas(html){const root=$('#exportRoot');root.innerHTML=html;await document.fonts.ready;await Promise.all([...root.querySelectorAll('img')].map(img=>img.decode()));return html2canvas(root.firstElementChild,{scale:2,backgroundColor:'#ffffff',logging:false,useCORS:false});}
async function exportVisual(q,type){if(type==='png'){const root=$('#exportRoot');root.innerHTML=quoteHTML(q);if(root.offsetHeight>14000)throw Error('Báo giá quá dài cho một ảnh. Hãy tải PDF nhiều trang.');const canvas=await renderCanvas(quoteHTML(q));const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('Không tạo được ảnh. Thử tải PDF.');download(blob,fileName()+'.png');return;}
const pages=[];let pos=0;while(pos<q.items.length){let best=1;for(let count=1;count<=q.items.length-pos;count++){const final=pos+count===q.items.length;$('#exportRoot').innerHTML=quoteHTML(q,q.items.slice(pos,pos+count),{continued:!final,page:pages.length+1,offset:pos,noAppendix:true});if($('#exportRoot').offsetHeight>1100&&count>1)break;best=count;if($('#exportRoot').offsetHeight>1100)break;}pages.push({items:q.items.slice(pos,pos+best),offset:pos});pos+=best;}const extra=q.type==='gate'&&gateAppendixHTML(q,esc)?['a','b']:[];const totalPages=pages.length+extra.length;
const pdf=new jspdf.jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});for(let i=0;i<pages.length;i++){if(i)pdf.addPage();const canvas=await renderCanvas(quoteHTML(q,pages[i].items,{continued:i<pages.length-1,page:(i+1)+'/'+totalPages,offset:pages[i].offset,noAppendix:true}));const width=210,height=canvas.height*width/canvas.width;const scale=Math.min(1,297/height);pdf.addImage(canvas.toDataURL('image/jpeg',.95),'JPEG',(210-width*scale)/2,0,width*scale,height*scale);}for(let j=0;j<extra.length;j++){pdf.addPage();const canvas=await renderCanvas(appendixPageHTML(q,extra[j],(pages.length+j+1)+'/'+totalPages));const width=210,height=canvas.height*width/canvas.width;const scale=Math.min(1,297/height);pdf.addImage(canvas.toDataURL('image/jpeg',.95),'JPEG',(210-width*scale)/2,0,width*scale,height*scale);}pdf.save(fileName()+'.pdf');}
