export const money=n=>new Intl.NumberFormat('vi-VN').format(n)+'đ';
export const number=n=>new Intl.NumberFormat('vi-VN').format(n);
export const clone=x=>JSON.parse(JSON.stringify(x));
export function roundProduct(a,b){const s=String(a);const parts=s.split('.');const scale=10n**BigInt((parts[1]||'').length);const q=BigInt(parts.join(''));const v=q*BigInt(Math.round(b));return Number((v+scale/2n)/scale);}
export function percentAmount(rate,value){const parts=String(rate).split('.');const denominator=100n*10n**BigInt((parts[1]||'').length);return Number((BigInt(parts.join(''))*BigInt(value)+denominator/2n)/denominator);}
export function totals(q){const subtotal=q.items.reduce((a,i)=>a+roundProduct(i.quantity,i.unitPrice),0);const reduction=percentAmount(q.discount||0,subtotal);const base=subtotal-reduction;const tax=(q.vat===''||q.vat==='included')?0:percentAmount(Number(q.vat),base);return {subtotal,reduction,base,tax,total:base+tax};}
export function checkQuote(q){if(!q||!Array.isArray(q.items)||q.items.length>500)throw Error('Báo giá không hợp lệ hoặc vượt 500 dòng.');if(!q.company||typeof q.company.accountNumber!=='string')throw Error('Thông tin công ty hoặc STK không hợp lệ.');for(const i of q.items){if(!i.name?.trim()||i.name.length>300||!i.unit?.trim()||!Number.isFinite(i.quantity)||i.quantity<=0||i.quantity>1000000||!Number.isFinite(i.unitPrice)||i.unitPrice<0||i.unitPrice>100000000000||!Number.isInteger(i.unitPrice))throw Error('Tên, đơn vị, số lượng hoặc đơn giá chưa hợp lệ. Giá là số nguyên VND; số lượng phải lớn hơn 0.');if(String(i.quantity).includes('e')||String(i.quantity).split('.')[1]?.length>4)throw Error('Số lượng tối đa 4 chữ số sau dấu phẩy.');}if(q.type!==undefined&&!['smart','gate'].includes(q.type))throw Error('Loại báo giá không hợp lệ.');if(q.mode!==undefined&&!['sum','options'].includes(q.mode))throw Error('Cách tính tổng không hợp lệ.');if(q.promo!==undefined&&(typeof q.promo!=='string'||q.promo.length>2000))throw Error('Ưu đãi tối đa 2000 ký tự.');for(const i of q.items){if(i.listPrice!==undefined&&(!Number.isInteger(i.listPrice)||i.listPrice<0||i.listPrice>100000000000))throw Error('Giá gốc phải là số nguyên VND.');}if(!Number.isFinite(q.discount)||q.discount<0||q.discount>100)throw Error('Chiết khấu phải từ 0 đến 100%.');if(q.vat!==''&&q.vat!=='included'&&![0,5,8,10].includes(Number(q.vat)))throw Error('VAT không hợp lệ.');return q;}
export function parsePrice(v){if(typeof v==='number'){if(Number.isInteger(v)&&v>=0)return v;throw Error('Giá phải là số nguyên VND.');}const s=String(v??'').trim().replace(/\s/g,'').replace(/(?:VND|VNĐ|đ)$/i,'');if(/^\d+(?:[.,]\d+)?k$/i.test(s))return Math.round(Number(s.slice(0,-1).replace(',','.'))*1000);if(/^\d+$/.test(s))return Number(s);if(/^\d{1,3}([.,])\d{3}(?:\1\d{3})*$/.test(s))return Number(s.replace(/[.,]/g,''));throw Error('Giá không rõ định dạng: '+v);}
export function normalizeProducts(rows){const seen=new Set();return rows.map((r,index)=>{const id=String(r.id??'').trim();const name=String(r.name??'').trim();const unit=String(r.unit??'').trim();if(!id||!name||!unit)throw Error(`Dòng ${index+1}: thiếu mã, tên hoặc đơn vị.`);if(seen.has(id))throw Error(`Dòng ${index+1}: mã ${id} bị trùng trong file.`);seen.add(id);let unitPrice;try{unitPrice=parsePrice(r.unitPrice);}catch(e){throw Error(`Dòng ${index+1}: ${e.message}`);}if(unitPrice>100000000000)throw Error(`Dòng ${index+1}: giá vượt giới hạn.`);return {id,name:name.slice(0,300),unit:unit.slice(0,30),unitPrice};});}
